### ISSUE TITLE
4.33.1版本无效果也不能升级

### ISSUE THREAD

**Issue by PDSCi996** [msbac/v2ray_bin#11]
我试着安装了4.33.1和4.33.0两个版本，安装33.0后界面只有v2ray而没有xray升级按钮，后来又安装了4.33.1版本，但是界面显示节点已经启动，但是没有任何效果，点击插件升级按钮失败，点击v2ray和xray升级也无效，看目录已经有4.34.0版本的升级了，不知道为何不能升级。

**Comment by cskmaband** [comment]
我也是，不過v2ray和xray更新到最新版本，對比之前不能更新的情況，現在應該是沒問題

**Comment by PDSCi996** [comment]
> 我也是，不過v2ray和xray更新到最新版本，對比之前不能更新的情況，現在應該是沒問題

请问你如何更新的，我这里点击更新按钮都提示失败了。

**Comment by cskmaband** [comment]
我是重新安裝一次，雖然版本顯示v4.331但是v2ray和xray都更新到v1.3

**Comment by cskmaband** [comment]
不過不知道為什麼整體連接v2ray的速度變慢，網速跑不起來

**Comment by PDSCi996** [comment]
> 不過不知道為什麼整體連接v2ray的速度變慢，網速跑不起來

有同感，我打开YouTube首页和缩略图感觉变慢了
