### ISSUE TITLE
梅林380上v2ray或xray更新時出現ssl拒絕連線

### ISSUE THREAD

**Issue by cskmaband** [msbac/v2ray_bin#9]
如題，請問還有其他方法更新v2ray或xray嗎？

**Comment by stiffyfoto** [comment]
【2021年02月05日 12:25:46】: ===================================================================
【2021年02月05日 12:25:46】:                 xray程序更新(Shell by sadog)
【2021年02月05日 12:25:46】: ===================================================================
【2021年02月05日 12:25:46】: 检测xray最新版本...
【2021年02月05日 12:25:50】: 检测到xray最新版本：v1.2.0
【2021年02月05日 12:25:53】: 当前已安装xray版本：v1.1.4
【2021年02月05日 12:25:54】: xray已安装版本号低于最新版本，开始更新程序...
【2021年02月05日 12:25:54】: 开始下载校验文件：md5sum.txt
【2021年02月05日 12:25:57】: md5sum.txt下载失败！
【2021年02月05日 12:25:57】: 开始下载xray程序
--2021-02-05 12:25:57--  https://raw.githubusercontent.com/msbac/v2ray_bin/main/380_armv5/xray/v1.2.0/xray
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
OpenSSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
Unable to establish SSL connection.
【2021年02月05日 12:26:00】: xray下载失败！
【2021年02月05日 12:26:00】: 校验下载的文件!
md5sum: can't open 'xray': No such file or directory
【2021年02月05日 12:26:00】: 文件校验通过!
【2021年02月05日 12:26:00】: 开始覆盖最新二进制!
【2021年02月05日 12:26:00】: 为了保证更新正确，先关闭xray主进程... 
【2021年02月05日 12:26:00】: 开始替换xray二进制文件... 
mv: can't rename '/tmp/xray/xray': No such file or directory
【2021年02月05日 12:26:04】: xray二进制文件替换成功... 
【2021年02月05日 12:26:05】: 开启xray进程... 
【2021年02月05日 12:26:07】: xray启动成功，pid：24654
【2021年02月05日 12:26:07】: ===================================================================

**Comment by cskmaband** [comment]
情況一樣啊，有什麼辦法解決？

**Comment by zhanglianbo35** [comment]
koolshare 梅林的wget 版本太老了， 换curl下载，查看 ss_xray.sh 中code里面有提示，
`	wget --no-check-certificate --timeout=20 --tries=1 $url_main/$1/xray   `
`	#curl -L -H "Cache-Control: no-cache" -o /tmp/xray/xray $url_main/$1/xray  `
把下面的反注释，上面的注释掉，其他所有的wget 都要按照类似下面的修改， 类似要修改的脚本还有 ss_v2ray.sh, ss_rule_update.sh
